BOARDS = {
    "main": "1149614311072230535",   # Budget Planner Spreadsheets & Finance Templates
    "debt": "1149614311072245490",   # Debt Payoff Planner
    "savings": "1149614311072245491",  # Savings Tracker Templates
    "biz": "1149614311072245492",    # Small Business Bookkeeping
}

P = [
 dict(key="debt", board="debt", cat="DEBT PAYOFF", name="Debt Snowball & Avalanche Tracker",
      hook="Get out of debt faster.", hook2="Snowball or avalanche? See which one wins.",
      stat_label="Your debt-free date", stat="Mar 2028", progress=62, progress_label="62% paid off",
      cols=["Debt", "Balance", "Rate", "Min"],
      rows=[["Credit card", "3,400", "22.9%", "95"], ["Car loan", "8,200", "6.5%", "240"],
            ["Student loan", "14,500", "4.9%", "160"], ["Medical", "900", "0%", "40"],
            ["Store card", "1,150", "26.9%", "35"], ["Personal loan", "4,800", "11.2%", "150"]],
      total=["Total", "32,950", "", "720"],
      checks=["Snowball vs avalanche side by side", "Debts ranked automatically", "Month-by-month payoff plan", "Debt-free date calculated"],
      seo=[
       ("Debt Snowball Spreadsheet – Get Out of Debt Faster (Excel & Google Sheets)",
        "Get out of debt faster with a debt snowball spreadsheet that ranks your debts and shows your debt free date. Debt payoff planner for Excel and Google Sheets, instant download. #debtsnowball #debtpayoff #debtfreejourney #payoffdebt #budgeting"),
       ("Debt Payoff Calculator Spreadsheet – See Your Debt Free Date",
        "Enter your balances and interest rates and this debt payoff calculator shows your debt free date and monthly plan. Credit card payoff tracker for Excel & Google Sheets. #debtpayoffcalculator #debtfree #creditcarddebt #moneytips #personalfinance"),
       ("Debt Avalanche vs Snowball Tracker – Printable Debt Payoff Planner",
        "Compare the debt avalanche vs debt snowball method in one debt payoff planner. Pay less interest and stay motivated. Excel & Google Sheets template, instant download. #debtavalanche #debtsnowball #debttracker #financialfreedom #budgettemplate"),
      ]),
 dict(key="budget", board="main", cat="BUDGETING", name="50/30/20 Monthly Budget Planner",
      hook="Know where every dollar goes.", hook2="The easiest budget you'll actually stick to.",
      stat_label="Left to save this month", stat="$640", progress=78, progress_label="78% of budget used",
      cols=["Category", "Planned", "Actual", "Left"],
      rows=[["Housing", "1,200", "1,200", "0"], ["Groceries", "450", "412", "38"],
            ["Transport", "220", "198", "22"], ["Savings", "600", "650", "-50"],
            ["Fun", "300", "275", "25"], ["Utilities", "180", "171", "9"]],
      total=["Total", "2,950", "2,906", "44"],
      checks=["50/30/20 split done for you", "Auto totals & over-budget flags", "12 monthly tabs + yearly view", "Beginner friendly"],
      seo=[
       ("Monthly Budget Spreadsheet for Beginners – 50/30/20 Budget Template",
        "A simple monthly budget spreadsheet for beginners using the 50/30/20 rule. Plan needs, wants and savings with auto totals. Budget template for Excel & Google Sheets. #budgetspreadsheet #budgetingforbeginners #503020budget #moneysavingtips #budgettemplate"),
       ("Budget Planner Google Sheets – Paycheck Budget Template",
        "Plan every paycheck with this budget planner for Google Sheets and Excel. Planned vs actual spending, over-budget alerts and savings tracking. Instant download. #budgetplanner #paycheckbudget #googlesheetsbudget #personalfinance #savemoney"),
       ("Simple Budget Template Excel – Monthly Budget Planner Printable",
        "Take control of your money with a simple monthly budget planner. 50/30/20 rule, 12 monthly tabs and a yearly summary. Excel & Google Sheets budget template. #budgettemplate #monthlybudget #financialplanning #frugalliving #budgetplanner"),
      ]),
 dict(key="subscription", board="main", cat="SUBSCRIPTIONS", name="Subscription & Bill Tracker",
      hook="Stop paying for things you forgot.", hook2="What do your subscriptions really cost per year?",
      stat_label="Yearly subscription cost", stat="$1,284", progress=35, progress_label="$420 could be cancelled",
      cols=["Service", "Billing", "Due", "Per year"],
      rows=[["Streaming", "Monthly", "5th", "191.88"], ["Gym", "Monthly", "1st", "420.00"],
            ["Cloud", "Annual", "Mar", "99.99"], ["Music", "Monthly", "12th", "131.88"],
            ["Phone", "Monthly", "20th", "360.00"], ["News", "Monthly", "8th", "80.00"]],
      total=["Total", "", "", "1,283.75"],
      checks=["Weekly, monthly & annual bills", "Real monthly and yearly cost", "Due-date overview", "Find what to cancel"],
      seo=[
       ("Bill Tracker Spreadsheet – Monthly Bills Organizer (Google Sheets)",
        "Never miss a due date with this bill tracker spreadsheet. See every monthly bill and subscription with its real yearly cost. Excel & Google Sheets, instant download. #billtracker #billsorganizer #monthlybills #budgeting #googlesheets"),
       ("Subscription Tracker Template – Find Subscriptions to Cancel & Save Money",
        "List all your subscriptions and see what they really cost per year. This subscription tracker helps you cancel what you do not use and save money. #subscriptiontracker #savemoney #moneysavingtips #frugalliving #budgettips"),
       ("Bill Payment Tracker Printable – Monthly Bill Checklist Spreadsheet",
        "Bill payment tracker and monthly bill checklist in one spreadsheet. Due dates, billing cycles and yearly totals calculated for you. Excel & Google Sheets. #billpaymentchecklist #billtracker #personalfinance #budgetplanner #organization"),
      ]),
 dict(key="habit", board="main", cat="HABITS", name="Monthly Habit Tracker",
      hook="Small habits. Big results.", hook2="Track 10 habits in 10 seconds a day.",
      stat_label="This month's streak", stat="21 days", progress=73, progress_label="73% completion rate",
      cols=["Habit", "Done", "Goal", "Rate"],
      rows=[["Workout", "22", "30", "73%"], ["Read", "27", "30", "90%"], ["No sugar", "18", "30", "60%"],
            ["Journal", "25", "30", "83%"], ["Water 2L", "28", "30", "93%"], ["Sleep 8h", "19", "30", "63%"]],
      total=["Average", "", "", "77%"],
      checks=["31-day grid for any month", "Completion rates auto-calculated", "Use on phone or print", "Up to 15 habits"],
      seo=[
       ("Habit Tracker Spreadsheet – Monthly Habit Tracker Google Sheets",
        "Build better habits with a monthly habit tracker spreadsheet. 31-day grid with automatic completion rates. Use in Google Sheets or Excel, or print it. #habittracker #habittrackerideas #selfcare #productivity #goals"),
       ("Printable Habit Tracker – 31 Day Habit Tracker Template",
        "Printable 31 day habit tracker template to track workouts, reading, water and more. Digital or print, instant download for Excel & Google Sheets. #printablehabittracker #monthlyhabittracker #selfimprovement #morningroutine #plannerideas"),
       ("Digital Habit Tracker – Daily Habit Tracker with Progress Stats",
        "A digital daily habit tracker that calculates your completion rate and streaks for you. Simple, clean and easy to use in Google Sheets and Excel. #digitalplanner #habittracker #selfdevelopment #healthyhabits #goalsetting"),
      ]),
 dict(key="meal", board="main", cat="MEAL PLANNING", name="Weekly Meal Planner + Grocery List",
      hook="Dinner, sorted for the week.", hook2="Plan once. Shop once. Save every week.",
      stat_label="Grocery budget this week", stat="$85", progress=64, progress_label="17 of 26 items checked",
      cols=["Day", "Breakfast", "Lunch", "Dinner"],
      rows=[["Mon", "Oats", "Wraps", "Pasta"], ["Tue", "Eggs", "Salad", "Tacos"], ["Wed", "Yogurt", "Soup", "Stir fry"],
            ["Thu", "Oats", "Leftovers", "Curry"], ["Fri", "Toast", "Bowl", "Pizza"], ["Sat", "Pancakes", "Sandwich", "Grill"]],
      total=None,
      checks=["7-day meal grid", "Grocery list with checkboxes", "Weekly food budget", "Reuse every week"],
      seo=[
       ("Weekly Meal Planner Template – Meal Planning Spreadsheet with Grocery List",
        "Plan your week of meals in minutes with this weekly meal planner template and grocery list. Save time and money on groceries. Excel & Google Sheets. #mealplanner #mealplanningideas #weeklymealplan #grocerylist #familymeals"),
       ("Meal Plan on a Budget – Printable Meal Planner & Grocery List",
        "Eat well on a budget with a printable meal planner and grocery list. Track your weekly food budget and stop wasting food. Instant download spreadsheet. #mealplanonabudget #budgetmeals #grocerybudget #frugalmeals #mealprep"),
       ("Digital Meal Planner Google Sheets – Family Meal Planning Template",
        "A digital meal planner for Google Sheets and Excel: breakfast, lunch and dinner grid plus a grocery checklist. Perfect for busy families. #digitalmealplanner #familymealplanning #mealprepideas #weeklyplanner #organizedhome"),
      ]),
 dict(key="savings", board="savings", cat="SAVINGS", name="Savings & Sinking Funds Tracker",
      hook="Save for everything, stress-free.", hook2="Emergency fund, vacation, new car: one tracker.",
      stat_label="Saved so far this year", stat="$4,350", progress=58, progress_label="58% of all goals reached",
      cols=["Goal", "Target", "Saved", "Per month"],
      rows=[["Emergency", "5,000", "2,900", "250"], ["Vacation", "2,400", "1,100", "200"], ["New car", "6,000", "1,800", "300"],
            ["Gifts", "600", "350", "50"], ["Home", "3,000", "900", "150"], ["Car repair", "800", "400", "60"]],
      total=["Total", "17,800", "7,450", "1,010"],
      checks=["Monthly amount per goal", "Countdown to each target date", "Emergency fund ready", "Progress bars built in"],
      seo=[
       ("Sinking Funds Tracker Spreadsheet – Savings Goals Tracker",
        "Save for every goal with a sinking funds tracker spreadsheet. Monthly amount per goal, progress bars and target dates. Excel & Google Sheets. #sinkingfunds #savingsgoals #savingschallenge #moneysavingtips #budgeting"),
       ("Emergency Fund Tracker – Savings Tracker Printable & Digital",
        "Build your emergency fund step by step with this savings tracker. See how much to save each month and watch your progress grow. Instant download. #emergencyfund #savingstracker #savemoney #financialgoals #personalfinance"),
       ("Savings Plan Template – Save Money Tracker for Google Sheets",
        "A savings plan template that tells you exactly how much to save per month for each goal: vacation, car, gifts and more. Excel & Google Sheets. #savingsplan #savemoneytracker #savingsgoal #frugalliving #budgetplanner"),
      ]),
 dict(key="networth", board="savings", cat="NET WORTH", name="Net Worth Tracker",
      hook="Watch your wealth grow.", hook2="The one number that shows your real progress.",
      stat_label="Net worth growth this year", stat="+$4,600", progress=45, progress_label="45% to your next milestone",
      cols=["Month", "Assets", "Debts", "Net worth"],
      rows=[["Jan", "42,100", "23,800", "18,300"], ["Feb", "43,050", "23,330", "19,720"], ["Mar", "44,400", "22,950", "21,450"],
            ["Apr", "45,200", "22,300", "22,900"], ["May", "46,050", "21,900", "24,150"], ["Jun", "46,900", "21,400", "25,500"]],
      total=None,
      checks=["Assets vs liabilities", "Monthly history auto-linked", "Growth chart included", "Milestones to aim for"],
      seo=[
       ("Net Worth Tracker Spreadsheet – Track Your Net Worth Monthly",
        "Track your net worth every month with this net worth tracker spreadsheet: assets, debts and growth chart. Excel & Google Sheets, instant download. #networth #networthtracker #financialindependence #wealthbuilding #moneygoals"),
       ("Net Worth Calculator Template – Assets and Liabilities Spreadsheet",
        "A simple net worth calculator: list your assets and liabilities and see your real net worth with monthly history. Excel & Google Sheets template. #networthcalculator #personalfinance #fire #investing #financialplanning"),
       ("Wealth Tracker Google Sheets – Financial Freedom Net Worth Planner",
        "Stay motivated on your financial freedom journey with a wealth tracker for Google Sheets. Monthly net worth, milestones and a growth chart. #financialfreedom #wealthtracker #googlesheets #moneymindset #networthgoals"),
      ]),
 dict(key="bookkeeping", board="biz", cat="SMALL BUSINESS", name="Small Business Bookkeeping",
      hook="Bookkeeping without the headache.", hook2="Income, expenses and profit, one sheet.",
      stat_label="Profit this month", stat="$6,400", progress=76, progress_label="76% profit margin",
      cols=["Category", "Income", "Expense", "Month"],
      rows=[["Sales", "8,400", "-", "Jun"], ["Supplies", "-", "1,150", "Jun"], ["Software", "-", "240", "Jun"],
            ["Shipping", "-", "610", "Jun"], ["Services", "1,200", "-", "Jun"], ["Ads", "-", "1,200", "Jun"]],
      total=["Total", "9,600", "3,200", "Jun"],
      checks=["Income & expense log", "Category summary, linked", "Monthly profit & loss", "No accounting app needed"],
      seo=[
       ("Small Business Bookkeeping Template – Simple Income & Expense Spreadsheet",
        "Simple bookkeeping for small business owners: log income and expenses and get a monthly profit and loss automatically. Excel & Google Sheets. #bookkeepingtemplate #smallbusinessowner #expensetracker #smallbusinesstips #entrepreneur"),
       ("Expense Tracker Spreadsheet for Small Business – Profit & Loss Template",
        "Track business expenses and income in one spreadsheet with a linked profit and loss summary. Great for Etsy sellers and side hustles. Instant download. #profitandloss #businessexpenses #etsysellertips #sidehustle #smallbusiness"),
       ("Bookkeeping Spreadsheet for Etsy Sellers & Side Hustles",
        "Easy bookkeeping spreadsheet for Etsy sellers, freelancers and side hustles. Categories, monthly summary and profit calculated for you. Excel & Google Sheets. #etsyseller #freelancer #bookkeeping #sidehustleideas #businessorganization"),
      ]),
 dict(key="metaads", board="biz", cat="MARKETING", name="Meta Ads Campaign Tracker",
      hook="Know which ads make money.", hook2="ROAS, CPA and CTR in one clean dashboard.",
      stat_label="Blended ROAS this month", stat="3.4x", progress=68, progress_label="68% of monthly ad budget spent",
      cols=["Campaign", "Spend", "ROAS", "CPA"],
      rows=[["Prospecting", "420", "2.8x", "14.20"], ["Retargeting", "180", "5.1x", "7.90"], ["Lookalike", "310", "3.4x", "11.60"],
            ["Video views", "150", "1.9x", "19.40"], ["Catalog", "260", "4.2x", "9.10"], ["Engagement", "90", "1.4x", "22.30"]],
      total=["Total", "1,410", "3.4x", "12.10"],
      checks=["ROAS, CPA & CTR auto-calculated", "Per-campaign spend log", "Facebook & Instagram ads", "Weekly performance view"],
      seo=[
       ("Facebook Ads Tracker Spreadsheet – Track ROAS & CPA (Google Sheets)",
        "Know which Facebook ads make money. This Facebook ads tracker spreadsheet calculates ROAS, CPA and CTR per campaign. Excel & Google Sheets. #facebookads #facebookadstips #roas #digitalmarketing #onlinebusiness"),
       ("Meta Ads Reporting Template – Ad Campaign Tracker for Small Business",
        "A simple Meta ads reporting template for small businesses and ecommerce stores. Log spend and results, get ROAS and CPA automatically. #metaads #instagramads #ecommercetips #marketingtips #smallbusinessmarketing"),
       ("Ad Spend Tracker for Ecommerce – Instagram & Facebook Ads Spreadsheet",
        "Track your ad spend and results across Instagram and Facebook ads with one spreadsheet. ROAS, CPA and weekly performance view. Instant download. #adspend #ecommercebusiness #shopifytips #facebookmarketing #instagrammarketing"),
      ]),
]
